---
testbed_id: "${USER}-remora"
cloud_provider: aws
token_file: "/Users/${USER}/.aws/credentials"
ssh_private_key_file: "/Users/${USER}/.ssh/aws"
regions:
  - us-east-1
specs: m5d.8xlarge
repository:
  url: https://github.com/scofield-mysten/sui
  commit: vanilla-orchestrator
node_parameters_path: "crates/remora-orchestrator/assets/node-parameters.yml"
client_parameters_path: "crates/remora-orchestrator/assets/client-parameters.yml"
dedicated_clients: 1
